### ISSUE TITLE
getting errors when doing a build robot-events-commands-server.js code in VS

### ISSUE THREAD

**Issue by jBachalo** [hybridgroup/cylon-api-socketio#2]
Getting the 4 following errors when I try and build  the demo code in VS

F:\robot-events-commands-server.js: line 1, col 1, Use the function form of "use strict".
F:\robot-events-commands-server.js: line 3, col 13, 'require' is not defined.
F:\robot-events-commands-server.js: line 36, col 9, 'after' is not defined.
F:\robot-events-commands-server.js: line 40, col 9, 'after' is not defined.

**Comment by jBachalo** [comment]
If I just comment out the use strict line, everything builds ok

**Comment by edgarsilva** [comment]
Did this work then? this looks like just JSHint warning and erros, maybe adding a .jshintrc would fix it.

**Comment by jBachalo** [comment]
yeah thanks, commenting out the strict works.

Still struggling with sending and receiving custom data along with an event.

Will post another github issue with just my custom emit and emit handler
code...

On Wed, Feb 18, 2015 at 3:05 PM, Edgar O Silva <notifications@github.com>
wrote:

> Did this work then? this looks like just JSHint warning and erros, maybe
> adding a .jshintrc would fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hybridgroup/cylon-api-socketio/issues/2#issuecomment-74937453>
> .
>



-- 
[c] 416.306.0036
[w] www.bitstream.ca
--------------------------------------------
"...all improvisation is life in search of a style."
            - Bruce Mau,'LifeStyle'

**Comment by jBachalo** [comment]
https://github.com/hybridgroup/cylon-api-socketio/issues/3

Any help or feedback in getting custom data working appreciated!


On Wed, Feb 18, 2015 at 3:50 PM, Jim Bachalo <bach44@gmail.com> wrote:

> yeah thanks, commenting out the strict works.
>
> Still struggling with sending and receiving custom data along with an
> event.
>
> Will post another github issue with just my custom emit and emit handler
> code...
>
> On Wed, Feb 18, 2015 at 3:05 PM, Edgar O Silva <notifications@github.com>
> wrote:
>
>> Did this work then? this looks like just JSHint warning and erros, maybe
>> adding a .jshintrc would fix it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hybridgroup/cylon-api-socketio/issues/2#issuecomment-74937453>
>> .
>>
>
>
>
> --
> [c] 416.306.0036
> [w] www.bitstream.ca
> --------------------------------------------
> "...all improvisation is life in search of a style."
>             - Bruce Mau,'LifeStyle'
>



-- 
[c] 416.306.0036
[w] www.bitstream.ca
--------------------------------------------
"...all improvisation is life in search of a style."
            - Bruce Mau,'LifeStyle'
