### ISSUE TITLE
Getting access to the actual socket

### ISSUE THREAD

**Issue by jBachalo** [hybridgroup/cylon-api-socketio#4]
From 
robot-events-commands-server.js
how would I get access to -or expose the socket object in the following method

*this.io.on('connection', function(socket) {*
in *lib/socket-master.js *?

**Comment by edgarsilva** [comment]
This is all handle internally by Cylon and not possible at the momment. All robots and devices with commands and events should be available and easy to access from socketio.

This seems to be working for you, so I'm closing this issue.
